consumes:
- application/json
info:
  description: TH Server. Handles asssets, routing, data.
  title: Telehealers backend
  version: 0.0.0
paths: {}
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: telehealers-token

security:
  - key: []

paths:
  /profile_pictures/{name}:
    get:
      description: Central endpoint for profile pictures
      produces:
        - image/png
      parameters:
        - name: name
          in: path
          type: string
          required: true
      responses:
        200:
          description: Fetched image
          schema:
            type: file
        default:
          description: Error response
          schema:
            $ref: './definitions.yml#/error'
  # Image CRUD APIs
  /file/upload:
    $ref: './file_store_api.yml#/upload'
  /file/download:
    $ref: './file_store_api.yml#/download'
  /file/remove:
    $ref: './file_store_api.yml#/remove'
  # Doctor CRUD APIs
  /doctor/register:
    $ref: './doctor_crud_api.yml#/register'
  /doctor/update:
    $ref: './doctor_crud_api.yml#/update'
  /doctor/remove:
    $ref: './doctor_crud_api.yml#/remove'
  /doctor/find:
    $ref: './doctor_crud_api.yml#/find'
  ## Yet to be tested
  /doctor/register/apply:
    $ref: './doctor_crud_api.yml#/registration_application'
  /doctor/register/pending_applications:
    $ref: './doctor_crud_api.yml#/view_pending_registration_application'
  /doctor/register/review:
    $ref: './doctor_crud_api.yml#/review_registration_application'
  /doctor/login:
    $ref: './doctor_crud_api.yml#/login'
  /doctor/patients:
    $ref: './doctor_crud_api.yml#/patients'
  /doctor/online:
    $ref: './doctor_crud_api.yml#/online'
  /doctor/services:
    $ref: './doctor_crud_api.yml#/find_services'
  # Patient CRUD APIs
  /patient/register:
    $ref: './patient_crud_api.yml#/register'
  /patient/update:
    $ref: './patient_crud_api.yml#/update'
  /patient/find:
    $ref: './patient_crud_api.yml#/find'
  /patient/remove:
    $ref: './patient_crud_api.yml#/remove'
  /patient/login:
    $ref: './patient_crud_api.yml#/login'
  # Patient Health Info APIs
  /patient/health_info/add:
    $ref: './patient_health_info_crud_api.yml#/add'
  /patient/health_info/find:
    $ref: './patient_health_info_crud_api.yml#/find'
  # Appointment CRUD APIs
  /appointment/register:
    $ref: './appointment_crud_api.yml#/register'
  /appointment/update:
    $ref: './appointment_crud_api.yml#/update'
  /appointment/remove:
    $ref: './appointment_crud_api.yml#/remove'
  /appointment/find:
    $ref: './appointment_crud_api.yml#/find'
  /appointment/count:
    $ref: './appointment_crud_api.yml#/count'
  # Medicine CRUD APIs
  /medicine/register:
    $ref: './entity_crud_api.yml#/register'
  /medicine/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medicine/update:
    $ref: './entity_crud_api.yml#/update'
  /medicine/find:
    $ref: './entity_crud_api.yml#/find'
  # Test CRUD APIs
  /medical/test/register:
    $ref: './entity_crud_api.yml#/register'
  /medical/test/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medical/test/update:
    $ref: './entity_crud_api.yml#/update'
  /medical/test/find:
    $ref: './entity_crud_api.yml#/find'
  # Advices CRUD APIs
  /medical/advice/register:
    $ref: './entity_crud_api.yml#/register'
  /medical/advice/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medical/advice/update:
    $ref: './entity_crud_api.yml#/update'
  /medical/advice/find:
    $ref: './entity_crud_api.yml#/find'
  # Prescription CRUD APIs
  /prescription/register:
    $ref: './prescription_crud.yml#/register'
  /prescription/update:
    $ref: './prescription_crud.yml#/update'
  /prescription/find:
    $ref: './prescription_crud.yml#/find'
  /prescription/remove:
    $ref: './prescription_crud.yml#/remove'
  # Service crud APIs
  /medical/services/register:
    $ref: './entity_crud_api.yml#/register'
  /medical/services/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medical/services/update:
    $ref: './entity_crud_api.yml#/update'
  /medical/services/find:
    $ref: './entity_crud_api.yml#/find'
  /medical/services/link/doctor:
    $ref: './service_link_crud_api.yml#/link'
  # Request admin approval
  /helpdesk/ticket/open:
    $ref: './helpdesk_crud_api.yml#/open'
  /helpdesk/ticket/update:
    $ref: './helpdesk_crud_api.yml#/update'
  /helpdesk/ticket/find:
    $ref: './helpdesk_crud_api.yml#/find'
  /helpdesk/ticket/find/count:
    $ref: './helpdesk_crud_api.yml#/count'

  /room_access_token:
    get:
      description: Returns a room access token. An access token is required by the room to perform any action.
      tags:
        - conferrencing
      parameters:
        - name: room 
          description: Room name for the conferrence. 
          in: query
          required: true
          type: string
        - name: id 
          description: Participant ID/name.
          in: query
          required: true
          type: string
      responses:
        200:
          description: Access token for the room x client.
          schema:
            type: string
        default:
          description: Failure
          schema:
            $ref: './definitions.yml#/error'
definitions:
  principal:
    type: string
