consumes:
- application/json
info:
  description: TH Server. Handles asssets, routing, data.
  title: Telehealers backend
  version: 0.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: telehealers-token

security:
  - key: []

paths:
  /profile_pictures/{name}:
    get:
      description: Central endpoint for profile pictures
      produces:
        - image/png
      parameters:
        - name: name
          in: path
          type: string
          required: true
      responses:
        200:
          description: Fetched image
          schema:
            type: file
        default:
          description: Error response
          schema:
            $ref: './definitions.yml#/error'
  # Doctor CRUD APIs
  /doctor/register:
    $ref: './doctor_crud_api.yml#/doctor/register'
  /doctor/update:
    $ref: './doctor_crud_api.yml#/doctor/update'
  /doctor/remove:
    $ref: './doctor_crud_api.yml#/doctor/remove'
  /doctor/find:
    $ref: './doctor_crud_api.yml#/doctor/find'
  # Patient CRUD APIs
  /patient/register:
    $ref: './patient_crud_api.yml#/register'
  /patient/update:
    $ref: './patient_crud_api.yml#/update'
  /patient/find:
    $ref: './patient_crud_api.yml#/find'
  /patient/remove:
    $ref: './patient_crud_api.yml#/remove'
  # Patient Health Info APIs
  /patient/health_info/add:
    $ref: './patient_health_info_crud_api.yml#/add'
  /patient/health_info/find:
    $ref: './patient_health_info_crud_api.yml#/find'
  # Appointment CRUD APIs
  /appointment/register:
    $ref: './appointment_crud_api.yml#/register'
  /appointment/update:
    $ref: './appointment_crud_api.yml#/update'
  /appointment/remove:
    $ref: './appointment_crud_api.yml#/remove'
  /appointment/find:
    $ref: './appointment_crud_api.yml#/find'
  # Medicine CRUD APIs
  /medicine/register:
    $ref: './entity_crud_api.yml#/register'
  /medicine/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medicine/update:
    $ref: './entity_crud_api.yml#/update'
  /medicine/find:
    $ref: './entity_crud_api.yml#/find'
  # Test CRUD APIs
  /medical/test/register:
    $ref: './entity_crud_api.yml#/register'
  /medical/test/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medical/test/update:
    $ref: './entity_crud_api.yml#/update'
  /medical/test/find:
    $ref: './entity_crud_api.yml#/find'
  # Advices CRUD APIs
  /medical/advice/register:
    $ref: './entity_crud_api.yml#/register'
  /medical/advice/remove:
    $ref: './entity_crud_api.yml#/remove'
  /medical/advice/update:
    $ref: './entity_crud_api.yml#/update'
  /medical/advice/find:
    $ref: './entity_crud_api.yml#/find'
  
  /room_access_token:
    get:
      description: Returns a room access token. An access token is required by the room to perform any action.
      tags:
        - conferrencing
      parameters:
        - name: room 
          description: Room name for the conferrence. 
          in: query
          required: true
          type: string
        - name: id 
          description: Participant ID/name.
          in: query
          required: true
          type: string
      responses:
        200:
          description: Access token for the room x client.
          schema:
            type: string
        default:
          description: Failure
          schema:
            $ref: './definitions.yml#/error'
definitions:
  principal:
    type: string
