version: "2"
services:
  db:
    image: mysql
    ports: 
      # TODO: Remove this port for better security in development environment.
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASENAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql
